### ISSUE TITLE
Test fails on Windows - quotemeta() missing

### ISSUE THREAD

**Issue by eserte** [bayashi/Plack-Middleware-ModuleInfo#1]
See http://www.cpantesters.org/cpan/report/c2307ba6-c8f5-11e4-bcdd-0907e0bfc7aa for a sample fail report on windows. Looking at the warnings

```
Unrecognized escape \M passed through in regex; marked by <-- HERE in m/file:.*Plack\M <-- HERE iddleware\ModuleInfo/ at t\01_basic.t line 70.
Unrecognized escape \M passed through in regex; marked by <-- HERE in m/file:.*Plack\Middleware\M <-- HERE oduleInfo/ at t\01_basic.t line 70.
```

it seems that somewhere a `quotemeta()` call or `\Q...\E` is missing.

**Comment by bayashi** [comment]
Indeed, I need a test for the test.
Anyway, I fixed it 0.03.
Thank you @eserte
